stages:
  - test
  - build
  - deploy
unit-test:
  stage: test
  script: "/Applications/Unity/Hub/Editor/2013.3.0f6/Unity.app/Contents/MacOS/Unity \
    -batchmode \
    -projectPath . \
    -runTests 
    -testPlatform editmode \
    -testCategory 2DToolbox \
    -logFile \
    -testResults ./unit-tests.xml"
  tags: 
    - unity
unity-build:
  stage: build
  script: echo 'Building... minor change for force update'
  tags: 
    - unity
playstore:
  stage: deploy
  script: echo 'Deploying...'
  tags: 
    - unity